apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-application-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: # путь к хранилищу
